benefits-button-container:hover - transition
aitmil/hugs-for-bugs pull request #80
Opened 2024-04-15 18:03 UTC by Hanna-Nahrebelna

Тільки одна зміна - додала кнопці transition: 2s

.benefits-button-container:hover {
    background-color: rgba(237, 59, 68);
    transition: 2s;
}

2024-04-15 18:33 UTC, aitmil requested changes

2024-04-15 18:33 UTC, aitmil commented on src/css/benefits.css
> +    transition: 2s;
так не правильно 
name | duration | behavior */
пропиши: background-color var(--transition)

2024-04-15 19:58 UTC, Hanna-Nahrebelna commented
Ми не працювали з var взагалі, тому я поправила, але не так, як ти просила. Не можу знайти в Гуглі приклад, як це зробити через background-color var(--transition).
Але я подивилася, що мій перший варіант цілком має право на життя, бо його використовують інші розробники також.
І мій перший варіант, і той, що я відправляю тобі зараз, працюють.
Якщо в тебе є приклад, як це зробити через background-color var(--transition), буду вдячна за пояснення.

2024-04-16 04:40 UTC, aitmil approved these changes

2024-04-16 04:40 UTC, merged